name: gencheminkaist
description: KAIST General Chemistry application.
publish_to: 'none'
version: 1.3.1+6

environment:
  sdk: ^3.5.0

dependencies:
  charset_converter: ^2.2.1
  dio: ^5.7.0
  firebase_analytics: ^11.3.3
  firebase_core: ^3.6.0
  firebase_remote_config: ^5.1.3
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.8.0
  flutter_riverpod: ^2.6.1
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  html: ^0.15.4
  html_to_pdf_plus: ^1.0.6
  json_annotation: ^4.9.0
  open_filex: ^4.5.0
  package_info_plus: ^8.1.0
  path_provider: ^2.1.5
  pdfrx: ^1.0.84
  riverpod_context: ^0.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/icons/ic_launcher.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/icons/ic_launcher.png'
  adaptive_icon_background: '#004191'
  adaptive_icon_foreground: 'assets/icons/ic_launcher_foreground.png'
