// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8IakphtYB8MdV0AIIz7hWgdNWMnnboVk',
    appId: '1:723715612492:android:fa5d88a3be0671c5',
    messagingSenderId: '723715612492',
    projectId: 'gencheminkaist',
    databaseURL: 'https://gencheminkaist.firebaseio.com',
    storageBucket: 'gencheminkaist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwu_Y7Sxq9ZpGravXJQNi9sgcNZX6chh8',
    appId: '1:723715612492:ios:02693ef458d2b26f0a79e9',
    messagingSenderId: '723715612492',
    projectId: 'gencheminkaist',
    databaseURL: 'https://gencheminkaist.firebaseio.com',
    storageBucket: 'gencheminkaist.appspot.com',
    androidClientId:
        '723715612492-de8id8mgmjoin2goevf8cgef98mlukeo.apps.googleusercontent.com',
    iosClientId:
        '723715612492-k7uslep33adlhkojneaae77vhq6u6n9j.apps.googleusercontent.com',
    iosBundleId: 'me.blog.ghwhsbsb123.gencheminkaist',
  );
}
